# Generated by Django 2.0.12 on 2020-01-02 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0004_auto_20200102_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsinfo',
            old_name='gunit',
            new_name='gprice1',
        ),
    ]
