# Generated by Django 2.0.12 on 2020-01-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0006_auto_20200102_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='gprice1',
            field=models.DecimalField(decimal_places=2, default='5000', max_digits=10, null=True, verbose_name='i7+512GB价格'),
        ),
    ]
