# Generated by Django 2.0.12 on 2020-01-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0005_goodsbrowser_browser_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='uanswer',
            field=models.CharField(default='', max_length=20, verbose_name='答案'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='uname',
            field=models.CharField(max_length=20, unique=True, verbose_name='用户名'),
        ),
    ]
