# Generated by Django 2.0.12 on 2020-01-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0006_auto_20200105_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='uquestion',
            field=models.CharField(default='', max_length=25, verbose_name='密保问题'),
        ),
    ]
