# Generated by Django 2.0.12 on 2020-01-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0007_userinfo_uquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='uanswer',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='答案'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='uquestion',
            field=models.CharField(default='', max_length=25, null=True, verbose_name='密保问题'),
        ),
    ]
